"""Add ActivationToken and submitter role

Revision ID: 4839b4a5262a
Revises: 0004_story_approval_timestamp
Create Date: 2026-10-01 17:06:34.896262
"""
from alembic import op
import sqlalchemy as sa

revision = '4839b4a5262a'
down_revision = '0004_story_approval_timestamp'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
