"""social_models

Revision ID: bd23fc0ccf41
Revises: 4839b4a5262a
Create Date: 2026-10-02 06:21:20.724143
"""
from alembic import op
import sqlalchemy as sa

revision = 'bd23fc0ccf41'
down_revision = '4839b4a5262a'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_public_profiles_username'), 'public_profiles', ['username'], unique=True)
    op.create_table('social_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_item_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['outreach_stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feed_item_id', name='uq_social_like_feed_item'),
    sa.UniqueConstraint('user_id', 'story_id', name='uq_social_like_story')
    )
    op.create_index(op.f('ix_social_likes_feed_item_id'), 'social_likes', ['feed_item_id'], unique=False)
    op.create_index(op.f('ix_social_likes_story_id'), 'social_likes', ['story_id'], unique=False)
    op.create_index(op.f('ix_social_likes_user_id'), 'social_likes', ['user_id'], unique=False)
    op.create_table('social_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('feed_item_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['outreach_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_shares_recipient_created', 'social_shares', ['recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_shares_recipient_id'), 'social_shares', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_social_shares_sender_id'), 'social_shares', ['sender_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_shares_sender_id'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_recipient_id'), table_name='social_shares')
    op.drop_index('ix_social_shares_recipient_created', table_name='social_shares')
    op.drop_table('social_shares')
    op.drop_index(op.f('ix_social_likes_user_id'), table_name='social_likes')
    op.drop_index(op.f('ix_social_likes_story_id'), table_name='social_likes')
    op.drop_index(op.f('ix_social_likes_feed_item_id'), table_name='social_likes')
    op.drop_table('social_likes')
    op.drop_index(op.f('ix_public_profiles_username'), table_name='public_profiles')
    op.drop_table('public_profiles')
    # ### end Alembic commands ###
